name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Use Node.js 16.16.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Install dependencies
        run: npm install
      - name: Compile with TypeScript
        run: npm run ts
      - name: Call LINT
        run: npm run lint
